version: '3'
services:
  app:
    container_name: 'npm'
    build:
      context: ./npm
    volumes:
      - './:/app'
    ports:
      - "80:80"
    entrypoint: ["sass", "--watch", "src/sass:src/css", "--style", "compressed"]